### PR TITLE
Add read_stream function

### PR DESCRIPTION
**Pull request by bucha**
Adding to my PR in `depot` (https://github.com/elixir-depot/depot/pull/2) here is an implementation of `read_stream` for `depot_s3`.

### CODE REVIEW

**Comment by mcrumm** [comment]
I would strongly consider using [`ExAws.S3.download_file/4`](https://hexdocs.pm/ex_aws_s3/ExAws.S3.html#download_file/4) to build a `%ExAws.S3.Download{}` operation. Then you should be able to use that op to invoke [`ExAws.S3.Download.build_chunk_stream/2`](https://hexdocs.pm/ex_aws_s3/ExAws.S3.Download.html#build_chunk_stream/2), which will return a stream, and that should be all you need. :)

**Comment by LostKobrakai** [comment]
@bucha It would be nice if you could adjust this to the change in the behaviour @mcrumm added with https://github.com/elixir-depot/depot/pull/3 as well as the suggestion for using `download_file/4`.

**Comment by JonRowe** [comment]
> I would strongly consider using ExAws.S3.download_file/4 to build a %ExAws.S3.Download{} operation. Then you should be able to use that op to invoke ExAws.S3.Download.build_chunk_stream/2, which will return a stream, and that should be all you need. :)

As someone who's just built this in their own app, I can say thats a problematic route if you are not in `us-east-1`, S3 wants you to use specific urls for those buckets, which ex_aws doesn't respect. e.g. I need to use bucket based urls to access mine which seem to be impossible to build automatically in ex_aws. This implementation wouldn't work for me either, but can easily fixed by adding the `virtual_host: true` to the `presigned_url` options.

**Comment by mcrumm** [comment]
@JonRowe thanks for that info! The actual [range request for the bytes](https://github.com/ex-aws/ex_aws_s3/blob/fb9bac4c51faedd07bdb795493ddbe65fc2e2e42/lib/ex_aws/s3/download.ex#L20) invokes `get_object/3`. I'm curious, how would one make the same request to a bucket in a different region? Is that the type of request that you're saying is impossible to build right now?

@bucha @LostKobrakai I completely glossed over all the Operation-based side effects of S3.Download the first time I looked at this. It appears its purpose is still to download the file to disk, _not_ to give you a lazy Enumerable over the byte range requests. https://github.com/ex-aws/ex_aws_s3/blob/v2.0.2/lib/ex_aws/s3/download.ex#L66

Ah, now I see that in-memory streams for Download were added in ex-aws/ex_aws_s3#60, but it's yet to be released.

**Comment by JonRowe** [comment]
> @JonRowe thanks for that info! The actual range request for the bytes invokes get_object/3. I'm curious, how would one make the same request to a bucket in a different region? Is that the type of request that you're saying is impossible to build right now?

There's something funny in how it all fits together, as `get_object/3` and `get_head_object/2` work correctly, but when using the `download` functions they don't seem to respect the config.

**Comment by bucha** [comment]
I've replaced the presigned URL approach with the code within the PR in `ex_aws_s3` @mcrumm mentioned (thanks!). This makes `depot_s3` lean as much as possible to `ex_aws_s3` functionality. The code is mostly just copied over though. As such, we should remove it as soon as there is a new release of `ex_aws_s3` with widespread adoption.

Concerning the issue about regions different than `us_east-1` mentioned by @JonRowe I don't really have a setup to test this situation right now, but isn't that something that should be addressed in `ex_aws_s3` itself?

**Comment by LostKobrakai** [comment]
I'd say so as well. I'll see if I can setup something on the weekend and regardless check this pr and merge it.

**Pull request merged**
